Task 1:

1.Write a function to compute 5/0 and use try/except to catch the exceptions

In [2]:
def divide(x, y):
    try:
        result = x / y
        print("Your Result is :", result)
    except ZeroDivisionError:
        print("Sorry ! Division by zero is not allowed. ")
        

divide(5,2)

divide(5,0)

Your Result is : 2.5
Sorry ! Division by zero is not allowed. 


In [ ]:
2.Implement a Python program to generate all sentences where subject is in ["Americans",
"Indians"] and verb is in ["Play", "watch"] and the object is in ["Baseball","cricket"].

In [8]:
subjects=["Americans ","Indians"]
verbs=["play","watch"]
objects=["Baseball","Cricket"]
#Using for loop
for x in subjects:
    for y in verbs:
        for z in objects:
            print(x+" "+y+" "+z+".")

Americans  play Baseball.
Americans  play Cricket.
Americans  watch Baseball.
Americans  watch Cricket.
Indians play Baseball.
Indians play Cricket.
Indians watch Baseball.
Indians watch Cricket.


In [11]:
#Using list comprehension 
sentence_list=[(sub+" "+vb+" "+ob) for sub in subjects for vb in verbs for ob in objects]
for sentence in sentence_list:
    print(sentence)

Americans  play Baseball
Americans  play Cricket
Americans  watch Baseball
Americans  watch Cricket
Indians play Baseball
Indians play Cricket
Indians watch Baseball
Indians watch Cricket


Task 2:

1.Write a function so that the columns of the output matrix are powers of the input vector.
The order of the powers is determined by the increasing boolean argument. Specifically, when
increasing is False, the i-th output column is the input vector raised element-wise to the power
of N - i - 1.
HINT:

In [15]:
import numpy as np
X = np.array([1, 2, 3, 4,5])
N=3
np.vander(X, N)

array([[ 1,  1,  1],
       [ 4,  2,  1],
       [ 9,  3,  1],
       [16,  4,  1],
       [25,  5,  1]])

In [16]:
np.column_stack([X**(N-1-i) for i in range(N)])

array([[ 1,  1,  1],
       [ 4,  2,  1],
       [ 9,  3,  1],
       [16,  4,  1],
       [25,  5,  1]], dtype=int32)

In [17]:
X = np.array([1, 2, 3, 4,5])
np.vander(X)

array([[  1,   1,   1,   1,   1],
       [ 16,   8,   4,   2,   1],
       [ 81,  27,   9,   3,   1],
       [256,  64,  16,   4,   1],
       [625, 125,  25,   5,   1]])

In [18]:
np.vander(X, increasing=True)

array([[  1,   1,   1,   1,   1],
       [  1,   2,   4,   8,  16],
       [  1,   3,   9,  27,  81],
       [  1,   4,  16,  64, 256],
       [  1,   5,  25, 125, 625]])

In [20]:
#The determinant of a square Vandermonde matrix is the product of the differences between the values of the input vector
np.linalg.det(np.vander(X))

287.9999999999977

In [21]:
(5-4)*(5-3)*(5-2)*(5-1)*(4-3)*(4-2)*(4-1)*(3-2)*(3-1)*(2-1)

288